name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install Tox
        run: pip install tox
      - name: Lint
        run: tox -e lint
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install Tox
        run: pip install tox
      - name: Build Docs
        run: tox -e docs
  dist:
    name: Dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install Tox
        run: pip install tox
      - name: Build Dist
        run: tox -e dist
  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install Tox
        run: pip install tox
      - name: Build Linkcheck
        run: tox -e linkcheck
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    name: Py ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox
        run: pip install tox
      - name: Test Sphinx 1.x
        env:
          SPHINX_VERSION: ==1.8.5
        run: tox -e py
      - name: Test Sphinx 2.x
        env:
          SPHINX_VERSION: ==2.4.5
        run: tox -e py
      - name: Test Sphinx Latest
        run: tox -e py
